// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjEnsF5B9AXaHYlp0i5sU7EzctyDTEnpg',
    appId: '1:943323910456:web:49d836e426951655a231cd',
    messagingSenderId: '943323910456',
    projectId: 'learning-flutter-lavish',
    authDomain: 'learning-flutter-lavish.firebaseapp.com',
    storageBucket: 'learning-flutter-lavish.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL00sghRxvKlIuBVtKYn9BKJx3d5vV-Ps',
    appId: '1:943323910456:android:d8421e5b0e41de33a231cd',
    messagingSenderId: '943323910456',
    projectId: 'learning-flutter-lavish',
    storageBucket: 'learning-flutter-lavish.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANnOGQPeb6dPAQAEVPQjohjNinn-wT5Pc',
    appId: '1:943323910456:ios:72a868dcfef8bc0da231cd',
    messagingSenderId: '943323910456',
    projectId: 'learning-flutter-lavish',
    storageBucket: 'learning-flutter-lavish.appspot.com',
    iosClientId: '943323910456-jatjbuq2jagito9dhvt1ohn5tn6e3nf7.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANnOGQPeb6dPAQAEVPQjohjNinn-wT5Pc',
    appId: '1:943323910456:ios:09c32c0927cb75b6a231cd',
    messagingSenderId: '943323910456',
    projectId: 'learning-flutter-lavish',
    storageBucket: 'learning-flutter-lavish.appspot.com',
    iosClientId: '943323910456-ovgjg5dhmh7m3ngotivr9cb2lub7dk4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
